### ISSUE TITLE
GitHub 2fa queries broken

### ISSUE THREAD

**Issue by hwine** [mozilla-services/foxsec-tools#113]
In at least 2 places:
- [x] missing new orgs in [this query](https://sql.telemetry.mozilla.org/queries/62650/source#160803)
    - No repo in new orgs were in metadata, so not reported. Fixed in [PR 1540](https://github.com/mozilla-services/foxsec/pull/1540)
- [x] mis-reported [2FA violations](https://sql.telemetry.mozilla.org/dashboard/firefox-secops-checklist-details?p_service_59954=Taskcluster&p_environment_59954=global&p_item_59954=Enforce%202FA&p_w53206_service_59954=Taskcluster&p_w53206_environment_59954=global&p_w53206_item_59954=Enforce%202FA) in some reports

**Comment by psiinon** [comment]
https://sql.telemetry.mozilla.org/dashboard/firefox-secops-checklist-details?p_service_59954=Taskcluster&p_environment_59954=global&p_item_59954=Enforce%202FA&p_w53206_service_59954=Taskcluster&p_w53206_environment_59954=global&p_w53206_item_59954=Enforce%202FA

**Comment by hwine** [comment]
2FA violations:
- query cited above (redash [Security Checklist Items](https://github.com/mozilla-services/foxsec-tools/blob/master/metrics/redash/security_checklist_items.sql)) expects correct data in `foxsec_metrics.checklist_combined` 
- `foxsec_metrics.checklist_combined` (athena [Checklist Combined](https://github.com/mozilla-services/foxsec-tools/blob/master/metrics/views/checklist_combined.sql)) expects correct data in `foxsec_metrics.github_checklist_latest`
- `foxsec_metrics.github_checklist_latest` (athena [GitHub Checklist Latest](https://github.com/mozilla-services/foxsec-tools/blob/master/metrics/views/github_checklist_latest.sql)) expects correct data in `foxsec_metrics.default_branch_protection_status`
- `foxsec_metrics.default_branch_protection_status` (athena [Default Branch Protection Status](https://github.com/mozilla-services/foxsec-tools/blob/master/metrics/views/default_branch_protection_status.sql))

**Comment by hwine** [comment]
@psiinon: My guess is you're treating missing data as a fail.

There are several things "wrong" with the query and database. By "wrong" I mean we're way off on definitions.

You're looking for a field called "Enforce 2FA", which is only defined at the organization level (not repository), so
1. The [current query][cq] iterates over repositories. That will never return meaningful information for 2FA.
2. The [collectors query](https://github.com/mozilla-services/foxsec-tools/blob/master/metrics/checklist/collectors/checklist.py#L46-L54) also includes the repo in the query, so that will also fail to produce the correct value.

Here's a [redash query](https://github.com/mozilla-services/foxsec-tools/blob/master/metrics/redash/repository_compliance_2fa.sql) that works for some definition of works. It's used in the [GitHub Status](https://sql.telemetry.mozilla.org/dashboard/github-status?p_organization_60731=) dashboard, the [Repository Compliance 2FA](https://sql.telemetry.mozilla.org/queries/62650/source#160803) query.

[cq]: https://sql.telemetry.mozilla.org/dashboard/firefox-secops-checklist-details?p_service_59954=Taskcluster&p_environment_59954=global&p_item_59954=Enforce%202FA&p_w53206_service_59954=Taskcluster&p_w53206_environment_59954=global&p_w53206_item_59954=Enforce%202FA

I suspect the solution will be to rejigger some of the checklist processing, so re-assigning to you.

**Comment by psiinon** [comment]
So I'm going to come up with an alternative analysis:

- I think the current dashboards and associated queries are all fine, as long as the data is right
- The problem is in the 2FS query you highlighted in checklist.py

Run this query:

```
SELECT 'Development' AS section, 'Enforce 2FA' AS item, a.service, '' as site, 'global' as environment,  
    CONCAT('https://', a.Host, '/', a.Org, '/', a.Repo) AS link,  
    every(b.body.two_factor_requirement_enabled) AS pass, '' as repo  
    FROM foxsec_metrics.metadata_repo_parsed AS a, foxsec_metrics.github_object AS b  
    JOIN (SELECT max(b2.date) AS MaxDay  FROM foxsec_metrics.github_object as b2) ON b.date = MaxDay  
    GROUP BY (service, a.Host, a.Org, a.Repo)
    ORDER BY (service, a.Host, a.Org, a.Repo)
```
All of the 'pass' values are false.
The fact that the results are per repo are (I think) irrelevant - thats just massaging the data to fit the format we need for the dashboards.
What we want is for the query to take the 2FA result at the org level and to apply it to all of the repos.
But its clearly not doing that right.
I dont think I created that query, it looks too advances for me!
Can you fix it?
If this doesnt make sense then lets have a call when you get in.

**Comment by hwine** [comment]
:) how quickly we push bad memories away - you're the only one to touch `collections.py` according to `git blame`!

Let's chat -- sounds like we have to "make ugly" some part of the code, and it just depends which part. Also, hopefully by discussing this now, it can be better in v2 -- at least we'll have an approach we agree upon.

**Comment by psiinon** [comment]
I'm still going to claim innocence - I had to google 'every' as an SQL operation, didnt even know it existed, so I'm sure someone else gave me that query...
And yeah, V2 should definitely be better than this (even if its just the docs)

**Comment by hwine** [comment]
Query failed in production. Queries run in Athena's default database, so all table names must be fully qualified:
```
SYNTAX_ERROR: line 8:9: Table awsdatacatalog.default.github_object does not exist
```

**Comment by hwine** [comment]
Now working in prod \o/
Total changes to implement: https://github.com/mozilla-services/foxsec-tools/compare/55f3312..be35f82 (ignore the trailing white space changes)
