### ISSUE TITLE
JSON -> schema generation scripts.

### ISSUE THREAD

**Issue by hwine** [mozilla-services/foxsec-tools#5]
This is a follow on to a [prior discussion](https://github.com/mozilla-services/foxsec-tools/pull/1#discussion_r215035393):

On my first review pass, I missed that these scripts are always manually run (only on initial add or upstream schema change). So no "flag day" to rename all the callers is needed.

Furthermore, the two use cases are more different than I thought (as I tried to write up the issue). I no longer think there is value in doing a merge. 

New proposal:
* [x] Land one script as ``metrics/utils/gen_athena_ddl`` ~~``metrics/utils/nested_json_to_athena_schema``~~ 
* [x] Document usage of ``gen_athena_ddl`` in ``metrics/utils/README.md``
* [ ] Land the other as ``metrics/utils/flat_json_to_athena_schema.py``
* [ ] Document usage of ``flat_json_to_athena_schema.py`` in ``metrics/utils/README.md``

@psiinon -- what do you think?

**Comment by psiinon** [comment]
Sounds good to me :)

**Comment by hwine** [comment]
@psiinon did you have a utility to help create the schemas for Athena tables? If so, I propose to check it in and close this bug :) (My idealistic dreams have been shattered.)

Otherwise, do you see value in having a csv -> Athena converter? I've not worked with non-json files. If not, we can also close this bug. :)

**Comment by psiinon** [comment]
@hwine yep: https://github.com/mozilla-services/foxsec-tools/pull/62 :)

**Comment by hwine** [comment]
We're done then.
