### ISSUE TITLE
Table github_checklist_latest definition wrong

### ISSUE THREAD

**Issue by psiinon** [mozilla-services/foxsec-tools#69]
The github_checklist_latest table is defined to have the following fields:

- environment
- link
- item
- pass
(etc)

Unfortunately they are in the wrong order, and the order is significant.
The order needs to be:

- environment
- item
- link
- pass
(item and link swapped).

This is a problem because checklist_combined merges checklist and github_checklist_latest and gets the github_checklist_latest fields end up in the wrong column.

If you run the following query on Athena you'll see what I mean:
`SELECT * FROM "foxsec_metrics"."checklist_combined" where service = 'AMO' and environment = 'global'`

**Comment by hwine** [comment]
Ah, right, from the union.

**Comment by psiinon** [comment]
Yeah :)

**Comment by hwine** [comment]
@psiinon where is the "official" order defined?

**Comment by psiinon** [comment]
thats defined by the 'checklist' table :) I'll update the Metrics Documentation to state that.

**Comment by hwine** [comment]
@psiinon made the change -- is the query correct now? I'm not sure what it should look like.
