### ISSUE TITLE
[MetaData] Repo status missing from Athena upload

### ISSUE THREAD

**Issue by hwine** [mozilla-services/foxsec-tools#95]
The newer ``codeRepositories`` object in the metadata has a field ``status`` that is not part of the current upload.

Without this data, repositories that have the status value ``deprecated`` cannot be skipped, generating false positives.  Blocks #86

**Comment by hwine** [comment]
Another alternative here, that would prevent future blockers, is to follow our convention of uploading a "RAW" version of the data.

In fact, this may have already been planned, as there is a ``foxsec-metrics/metadata/metadata_json/metadata.json`` that exists. But it has not been updated since 2019-03-12.

**Comment by hwine** [comment]
Things are a bit confusing to me at the moment. In S3:

| **File**                               | **Last Mod Date**                   |
|--------------------------------------|-----------------------------------|
| `metrics/metadata/metadata_json`     | Mar 12, 2019 11:48:52 AM GMT-0700 |
| `metrics/metadata/raw/metadata.json` | Jan 20, 2020 4:02:18 PM GMT-0800  |

The former is used in athena for the table `foxsec_metrics.metadata`. The later is not (currently) mapped to a table. No sql file exists for either file.

In redash, the `foxsec_metrics.metadata` table is used in 39 queries. Can it really be using data from 10 months ago?

@psiinon -- if the above sounds like it's a correct description of the current situation, then I think the changes in #112 is the right way to get us back to using current metadata.

If my analysis above isn't correct, then please suggest an alternative way to get current metadata available for reporting.

**Comment by psiinon** [comment]
Sorry, I'm still a bit brain dead thanks to this cold, but I'll try to catch up :/
It looks like the 'original' metadata tables were:

- metadata_repos
- metadata_services
- metadata_urls

The schema for all of these is in github (but I havnt checked if its exactly up to date) https://github.com/mozilla-services/foxsec-tools/tree/master/metrics/metadata/schemas

You added the raw support via https://github.com/mozilla-services/foxsec-tools/commit/0ba45f0f38da1b139010ba9600e1bbd96d7bfc3d#diff-a9346e6a20d9c39467833aacc47b0f5a

The metrics/metadata/metadata_json file/table does look to be out of date, and I'm not sure where it came from :/ which queries are using it?

**Comment by hwine** [comment]
> The metrics/metadata/metadata_json file/table does look to be out of date, and I'm not sure where it came from :/ which queries are using it?

Mostly ones that I assume (by name) were you:
```bash
$ cd metrics # in foxsec-tools repo
$ grep -rlw metadata redash/ views/ | grep '\.sql$' | sort
redash/dependencies_per_repo_and_package_manager.sql
redash/foxsec_dependencies_alert_details_for_packages_over_time.sql
redash/foxsec_dependencies_alert_summaries.sql
redash/foxsec_dependencies_packages.sql
redash/foxsec_dependencies_repos_with_package.sql
redash/foxsec_distinct_org_from_gh_meta.sql
redash/foxsec_distinct_repo_from_gh_meta.sql
redash/foxsec_fraud_alerts_for_service_by_category_all_time.sql
redash/foxsec_fraud_alerts_for_service_by_category_last_24_hours.sql
redash/foxsec_fraud_alerts_for_service_by_category_last_hour.sql
redash/foxsec_fraud_alerts_for_service_by_category_last_month.sql
redash/foxsec_fraud_alerts_for_service_by_category_last_week.sql
redash/foxsec_fraud_amo_alerts_and_restrictions.sql
redash/foxsec_fraud_amo_restrictions_by_unique_ip.sql
redash/foxsec_fraud_authprofile_new_vs_known_ips.sql
redash/foxsec_fraud_customs_alerts_by_category_over_time.sql
redash/foxsec_fraud_customs_alerts_by_country_over_time.sql
redash/foxsec_fraud_httprequest_alerts_by_category_over_time.sql
redash/foxsec_fraud_httprequest_alerts_by_country_over_time.sql
redash/foxsec_fraud_httprequest_alerts_by_service_over_time.sql
redash/foxsec_fraud_live_transforms.sql
redash/foxsec_fraud_live_transforms_for_resource.sql
redash/foxsec_fraud_site_accounts_firefox_com.sql
redash/foxsec_fraud_site_addons_mozilla_org.sql
redash/foxsec_fraud_site_auth.sql
redash/foxsec_fraud_site_bugzilla_mozilla_org.sql
redash/foxsec_fraud_site_getpocket_com.sql
redash/foxsec_fraud_site_monitor_firefox_com.sql
redash/foxsec_fraud_site_premium_firefox_com.sql
redash/foxsec_fraud_site_prod_normandy_prod_cloudops_mozgcp_net.sql
redash/foxsec_fraud_site_send_firefox_com.sql
redash/foxsec_fraud_site_sentry_prod_mozaws_net.sql
redash/foxsec_fraud_sites.sql
redash/foxsec_metadata_bugzilla_components.sql
redash/foxsec_metadata_repos.sql
redash/foxsec_metsdata_list_of_services.sql
redash/foxsec_svc_repos_w_url_and_status.sql
redash/secops_dependent_packages_nightly_run.sql
redash/vulnerability_alerts_by_github_org_and_repo.sql
```
Which is 40 queries, and ~111 lines. There are a few false positives on `dependency-metadata-*`.

While I assume landing the PR won't hurt those queries, I really know nothing about how their used, and if it might cause a spike that will rattle management.

**Comment by hwine** [comment]
> The schema for all of [the originial tables] is in github (but I havnt checked if its exactly up to date) 

We shouldn't need to worry about out-of-date -- we only add fields, so existing code works.

> You added the raw support via 0ba45f0

Right - Part of the question is should I do a hack of grabbing prod data from the `raw/` directory, or be consistent by duplicating the raw file into the `metadata_json` directory.
